{
    'name': 'Azmee Shipping & Logistic',
    'version': '18.4',
    'summary': 'Tutorial Odoo',
    'description': '',
    'category': 'Custom',
    'author': 'Azmee',
    'website': '',
    'license': 'LGPL-3',
    'depends': ['base', 'stock', 'product'],
    'data': [
        'data/ir_sequence.xml',
        'security/shipping_security.xml',
        'security/ir.model.access.csv',
        'views/vehicle_views.xml',
        'views/vehicle_brand_views.xml',
        'views/vehicle_model_views.xml',
        'views/vehicle_type_views.xml',
        'views/spb_views.xml',
        'views/pl_issue_views.xml',
        'views/shipment_views.xml',
        'views/pl_receipt_views.xml',
        'wizards/wizard_confirm_pl_issue_views.xml',
        'wizards/wizard_shipping_report_views.xml',
    ],
    'demo': [],
    'installable': True,
    'auto_install': False,
}